import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { network } from "hardhat";
import { encodeAbiParameters, keccak256 } from "viem";

const { viem } = await network.create();

/**
 * The acceptance suite. Your CertificateRegistry must pass every test here.
 * Do not edit this file: it is the specification in executable form, and it is
 * what will be run against your submission.
 */

async function deployed() {
  const [admin, issuer, alice, bob] = await viem.getWalletClients();
  const registry = await viem.deployContract("CertificateRegistry", []);
  return { registry, admin, issuer, alice, bob };
}

const expectedId = (recipient: string, issuer: string, courseName: string) =>
  keccak256(encodeAbiParameters(
    [{ type: "address" }, { type: "address" }, { type: "string" }],
    [recipient as `0x${string}`, issuer as `0x${string}`, courseName],
  ));

describe("acceptance: roles", function () {
  it("makes the deployer the admin and an issuer", async function () {
    const { registry, admin } = await deployed();
    assert.equal((await registry.read.admin()).toLowerCase(), admin.account.address.toLowerCase());
    assert.equal(await registry.read.isIssuer([admin.account.address]), true);
  });

  it("lets the admin add and remove issuers, and emits both events", async function () {
    const { registry, admin, issuer } = await deployed();
    assert.equal(await registry.read.isIssuer([issuer.account.address]), false);

    await viem.assertions.emitWithArgs(
      registry.write.addIssuer([issuer.account.address]),
      registry, "IssuerAdded", [issuer.account.address, admin.account.address]);
    assert.equal(await registry.read.isIssuer([issuer.account.address]), true);

    await viem.assertions.emitWithArgs(
      registry.write.removeIssuer([issuer.account.address]),
      registry, "IssuerRemoved", [issuer.account.address, admin.account.address]);
    assert.equal(await registry.read.isIssuer([issuer.account.address]), false);
  });

  it("refuses role changes from anyone but the admin", async function () {
    const { registry, issuer, alice } = await deployed();
    await assert.rejects(
      registry.write.addIssuer([alice.account.address], { account: issuer.account.address }),
      /IssuerOnly/);
  });

  it("refuses to add the same issuer twice, or remove one that is not an issuer", async function () {
    const { registry, issuer } = await deployed();
    await registry.write.addIssuer([issuer.account.address]);
    await assert.rejects(registry.write.addIssuer([issuer.account.address]), /AlreadyAnIssuer/);
    await registry.write.removeIssuer([issuer.account.address]);
    await assert.rejects(registry.write.removeIssuer([issuer.account.address]), /NotAnIssuer/);
  });

  it("refuses the zero address as an issuer", async function () {
    const { registry } = await deployed();
    await assert.rejects(
      registry.write.addIssuer(["0x0000000000000000000000000000000000000000"]), /ZeroAddress/);
  });
});

describe("acceptance: identity", function () {
  it("computes a certificate id anyone can recompute", async function () {
    const { registry, admin, alice } = await deployed();
    const id = await registry.read.certificateId([
      alice.account.address, admin.account.address, "Blockchain Systems"]);
    assert.equal(id, expectedId(alice.account.address, admin.account.address, "Blockchain Systems"));
  });

  it("gives different ids for different recipients, issuers, and courses", async function () {
    const { registry, admin, issuer, alice, bob } = await deployed();
    const base = await registry.read.certificateId([alice.account.address, admin.account.address, "A"]);
    const otherRecipient = await registry.read.certificateId([bob.account.address, admin.account.address, "A"]);
    const otherIssuer = await registry.read.certificateId([alice.account.address, issuer.account.address, "A"]);
    const otherCourse = await registry.read.certificateId([alice.account.address, admin.account.address, "B"]);
    assert.equal(new Set([base, otherRecipient, otherIssuer, otherCourse]).size, 4);
  });
});

describe("acceptance: issuing", function () {
  it("issues a certificate, stores every field, and emits the event", async function () {
    const { registry, admin, alice } = await deployed();
    const id = expectedId(alice.account.address, admin.account.address, "Blockchain Systems");

    await viem.assertions.emitWithArgs(
      registry.write.issue([alice.account.address, "Blockchain Systems", 91]),
      registry, "CertificateIssued",
      [id, alice.account.address, admin.account.address, "Blockchain Systems", (v: bigint) => v > 0n]);

    const record = await registry.read.get([id]);
    assert.equal(record.recipient.toLowerCase(), alice.account.address.toLowerCase());
    assert.equal(record.issuer.toLowerCase(), admin.account.address.toLowerCase());
    assert.equal(record.courseName, "Blockchain Systems");
    assert.equal(record.grade, 91);
    assert.equal(record.revoked, false);
    assert.ok(record.issuedAt > 0n);
    assert.equal(await registry.read.isValid([id]), true);
    assert.equal(await registry.read.totalIssued(), 1n);
  });

  it("lets an added issuer issue, and refuses everyone else", async function () {
    const { registry, issuer, alice } = await deployed();
    await assert.rejects(
      registry.write.issue([alice.account.address, "A", 50], { account: issuer.account.address }),
      /NotAnIssuer|IssuerOnly/);
    await registry.write.addIssuer([issuer.account.address]);
    await registry.write.issue([alice.account.address, "A", 50], { account: issuer.account.address });
    assert.equal(await registry.read.totalIssued(), 1n);
  });

  it("refuses an empty course name and the zero address", async function () {
    const { registry, alice } = await deployed();
    await assert.rejects(registry.write.issue([alice.account.address, "", 50]), /EmptyField/);
    await assert.rejects(
      registry.write.issue(["0x0000000000000000000000000000000000000000", "A", 50]), /ZeroAddress/);
  });

  it("refuses to issue the same certificate twice", async function () {
    const { registry, alice } = await deployed();
    await registry.write.issue([alice.account.address, "A", 50]);
    await assert.rejects(registry.write.issue([alice.account.address, "A", 60]), /CertificateExists/);
  });

  it("keeps a per-recipient list in issue order", async function () {
    const { registry, admin, alice } = await deployed();
    await registry.write.issue([alice.account.address, "First", 50]);
    await registry.write.issue([alice.account.address, "Second", 60]);
    const ids = await registry.read.certificatesOf([alice.account.address]);
    assert.deepEqual([...ids], [
      expectedId(alice.account.address, admin.account.address, "First"),
      expectedId(alice.account.address, admin.account.address, "Second"),
    ]);
  });

  it("returns an empty list for someone with no certificates", async function () {
    const { registry, bob } = await deployed();
    assert.deepEqual([...(await registry.read.certificatesOf([bob.account.address]))], []);
  });
});

describe("acceptance: revocation", function () {
  it("revokes a certificate, records the reason, and emits the event", async function () {
    const { registry, admin, alice } = await deployed();
    await registry.write.issue([alice.account.address, "A", 50]);
    const id = expectedId(alice.account.address, admin.account.address, "A");

    await viem.assertions.emitWithArgs(
      registry.write.revoke([id, "issued in error"]),
      registry, "CertificateRevoked", [id, admin.account.address, "issued in error"]);

    const record = await registry.read.get([id]);
    assert.equal(record.revoked, true);
    assert.equal(record.revocationReason, "issued in error");
    assert.equal(await registry.read.isValid([id]), false);
  });

  it("leaves the certificate readable after revocation", async function () {
    const { registry, admin, alice } = await deployed();
    await registry.write.issue([alice.account.address, "A", 50]);
    const id = expectedId(alice.account.address, admin.account.address, "A");
    await registry.write.revoke([id, "reason"]);
    const record = await registry.read.get([id]);
    assert.equal(record.courseName, "A");
    assert.equal(record.grade, 50);
    assert.equal(await registry.read.totalIssued(), 1n, "revoking does not un-issue");
  });

  it("refuses to revoke twice, to revoke what does not exist, or with an empty reason", async function () {
    const { registry, admin, alice } = await deployed();
    await registry.write.issue([alice.account.address, "A", 50]);
    const id = expectedId(alice.account.address, admin.account.address, "A");
    await assert.rejects(registry.write.revoke([id, ""]), /EmptyField/);
    await registry.write.revoke([id, "reason"]);
    await assert.rejects(registry.write.revoke([id, "again"]), /AlreadyRevoked/);
    await assert.rejects(
      registry.write.revoke([`0x${"11".repeat(32)}`, "reason"]), /CertificateNotFound/);
  });

  it("refuses revocation from an account that is not an issuer", async function () {
    const { registry, admin, alice } = await deployed();
    await registry.write.issue([alice.account.address, "A", 50]);
    const id = expectedId(alice.account.address, admin.account.address, "A");
    await assert.rejects(
      registry.write.revoke([id, "reason"], { account: alice.account.address }),
      /NotAnIssuer|IssuerOnly/);
  });

  it("reports an unknown certificate as invalid rather than reverting", async function () {
    const { registry } = await deployed();
    assert.equal(await registry.read.isValid([`0x${"22".repeat(32)}`]), false);
    await assert.rejects(registry.read.get([`0x${"22".repeat(32)}`]), /CertificateNotFound/);
  });
});
